name: CI

on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: list files
        run: ls -ltra

      - name: run shell comman
        run: echo "aldod and zuz"
